DROP DATABASE IF EXISTS hw11_DB;

CREATE DATABASE hw11_DB;

USE hw11_DB;

CREATE TABLE departments (
  id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);

CREATE TABLE roles (
  id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);

CREATE TABLE employees (
  id INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);